### PR TITLE
Tweak onboarding and developer docs

### PR DESCRIPTION
**Pull request by brandonlenz**
#  #

## 🗣 Description ##

Tests a signed commit after following onboarding instructions.

Relates to: https://github.com/cisagov/getgov/issues/552

## 💭 Motivation and context ##

The change isn't required, but the small doc updates might be helpful for future onboardees.

Confirms I am able to sign commits with my newly created gpg key

### CODE REVIEW

**Comment by brandonlenz** [comment]
Noting also that it appears most folks won't have access to the Team charter in its current location. Is there a better place for that, or is that intentional?

https://github.com/cisagov/getgov/pull/571/files#diff-54f276e9c7d00997a349a8ef4719a91e0645495dd6c3c88b3c86822b2e2dd2c6R45

**Comment by brandonlenz** [comment]
deploy failure, missing a credential, or incorrect credential?:

```Run cf login -a https://api.fr.cloud.gov/ -u $CF_USERNAME -p $CF_PASSWORD -o cisa-getgov-prototyping -s bl
  cf login -a https://api.fr.cloud.gov/ -u $CF_USERNAME -p $CF_PASSWORD -o cisa-getgov-prototyping -s bl
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    DEPLOY_NOW: thanks
    ENVIRONMENT: bl
    CF_USERNAME: ***
    CF_PASSWORD: ***
API endpoint: https://api.fr.cloud.gov/


Authenticating...
Credentials were rejected, please try again.

Password: API endpoint:   https://api.fr.cloud.gov/
API version:    3.137.0
Not logged in. Use 'cf login' or 'cf login --sso' to log in.
Unable to authenticate.
FAILED
Error: Process completed with exit code 1.
```

**Comment by brandonlenz** [comment]
Security check failure, would not have surprised me if there was an automation catching me checking in the .env-example with secret-sounding variable names, but from the output, I'm not clear that that's the issue:

```
WARN-NEW: Non-Storable Content [10049] x 12 
	http://app:8080/openid/login/ (500 Internal Server Error)
	http://app:8080 (200 OK)
	http://app:8080/ (200 OK)
	http://app:8080/public/css/styles.css (404 Not Found)
	http://app:8080/public/debug_toolbar/css/print.css (200 OK)
WARN-NEW: Permissions Policy Header Not Set [10063] x 11 
	http://app:8080 (200 OK)
	http://app:8080/ (200 OK)
	http://app:8080/edit/ (404 Not Found)
	http://app:8080/openid/login/ (500 Internal Server Error)
	http://app:8080/public/css/styles.css (404 Not Found)
FAIL-NEW: Timestamp Disclosure - Unix [10096] x 1 
	http://app:8080/openid/login/ (500 Internal Server Error)
FAIL-NEW: 1	FAIL-INPROG: 0	WARN-NEW: 2	WARN-INPROG: 0	INFO: 0	IGNORE: 0	PASS: 57
Automation plan failures:
	Job report failed to generate report: /zap/wrk/zap_report.html
Error: Process completed with exit code 1.
```

**Comment by loganmeetsworld** [comment]
CF issue fixed! I used the rotate credentials script and it is now working. Might've been an errant space in one of the variables saved in GH the first time or something.

**Comment by brandonlenz** [comment]
Looks like the OWASP error was indeed a fluke! Didn't see it locally when I ran owasp 🤷🏻

**Pull request merged**
