### PR TITLE
(Not on a sandbox) Ticket #1701: Prevent AO modification for federal and tribal

### LINKED ISSUE #1701: Prevent federal agency and tribal users from modifying their AO
### Issue description

Because we know the names/titles of the AO for federal agencies and tribal governments, and because the AO for these organizations is more-directly tied to their authorization (via DOTGOV Act rules and/or [M-23-10](https://www.whitehouse.gov/wp-content/uploads/2023/02/M-23-10-DOTGOV-Act-Guidance.pdf)) we should prevent domain managers of these domain types from updating their AO. 

These users may know before us that their AO has changed, however. Let's add content to direct the user to let us know it's changed, which we can then confirm and update.

### Acceptance criteria

- [ ] A domain manager for a federal or a tribal domain cannot edit their AO, but they can see it
- [ ] Content is written (for a tooltip?) telling a domain manager why they cannot update their AO and what they should do if they believe it should be updated

### Additional context

_No response_

### Links to other issues

🔄 Related to #1635 (where we're planning to remove the AO from the request form, though this issue is about the domain management experience)

### PR DESCRIPTION
**Pull request by zandercymatics**
## Ticket

Resolves #1701

## Changes

- Adds disabled styling in _forms.scss
- Modifies backend logic in forms/domain.py to deal with updates to AO and org
- Modifies domain_authorizing_official.html to add conditional edit logic if not federal or tribal
- Modifies domain_org_name_address (and the underlying form) to display a disabled input for Federal Agency
- Adds unit tests
- Modifies views/domain.py to determine when fields on the underlying form should be disabled

## Context for reviewers

**NOTE FOR DESIGNERS: After[ this ticket](https://github.com/cisagov/manage.get.gov/pulls) is reviewed, this PR will be put on a sandbox** 

This PR only affects domains that are Tribal or Federal. Other domains should be unaffected and their behavior should be unchanged.

The changes are as follows:
1. For Federal domains, "Federal Agency" is now readonly and not editable. 
2. For Tribal domains, "Organization Name" is now readonly and not editable
3. For both Federal AND Tribal domains, Authorizing Official (every field) is not editable

Note that 1. and 2. may be consolidated given feedback from product

## Setup
Create an (approved) domain in the "Tribal" state and the "Federal" state. Try to make modifications to the conditions listed above.

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [x] Checked that the design translated visually
- [x] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [x] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [x] Checked keyboard navigability
- [x] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [x] Tested with multiple browsers (check off which ones were used)
  - [x] Chrome
  - [x] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

### CODE REVIEW

**Review by therealslimhsiehdy — COMMENTED** [review]
**Federal:**
Authorizing Official greyed out:
Screenshot 2024-03-07 at 5 27 34 PM
Org name greyed out:
Screenshot 2024-03-07 at 5 28 39 PM


**Tribal:**
AO greyed out:
Screenshot 2024-03-07 at 5 33 33 PM

Org name greyed out:
Screenshot 2024-03-07 at 5 33 21 PM

**Non-federal or tribal (I did city):**
Able to edit both org name and AO and not greyed out
Screenshot 2024-03-07 at 5 39 25 PM
Screenshot 2024-03-07 at 5 39 42 PM

I tested this locally and will skimmed the code and it looks good, will do another round tomorrow and leave comments then!

**Review by therealslimhsiehdy — APPROVED** [review]
I looked over this twice, and I genuinely do not have any commentary and it looks good to me. The UI changes, the biz logic code + tests look great!

**Comment by gabydisarli** [comment]
@zandercymatics Looking this over and I'm realizing we are missing a line of content here. On the organization page for tribal government users, can you add this line before the required fields line?

> Your organization name can’t be updated here. To suggest an update, email [help@get.gov](mailto:help@get.gov).

**Review by gabydisarli — APPROVED** [review]
LGTM!

**Pull request merged**
