### PR TITLE
Follow sentence case for "Withdraw request"

### PR DESCRIPTION
**Pull request by michelle-rago**
# Follow sentence case for "Withdraw request" #

- Changed "Withdraw Request" to "Withdraw request"

### CODE REVIEW

**Comment by michelle-rago** [comment]
@kewlguy781 Hmm, I don't know what the error is here. Do you??

**Comment by kewlguy781** [comment]
This fail the test case because the test case do look for that part that you have edit. See this line in this file:

  File "/app/registrar/tests/test_views.py", line 1330, in test_application_withdraw
    withdraw_page = detail_page.click("Withdraw Request")

you will need to change that part as well. 

@michelle-rago

**Review by neilmb — APPROVED** [review]
LGTM, thanks again @michelle-rago for being willing to make these changes directly in this code repo.

**Comment by michelle-rago** [comment]
> This fail the test case because the test case do look for that part that you have changed. See this line in this file:
> 
> File "/app/registrar/tests/test_views.py", line 1330, in test_application_withdraw withdraw_page = detail_page.click("Withdraw Request")
> 
> you will need to change that part as well.
> 
> @michelle-rago

Thanks, @kewlguy781!

**Pull request merged**
