### PR TITLE
show requested domain and alternate domains on manage screen; formatt…

### LINKED ISSUE #685: [Bug]: Show requested domain and any alternate requests when managing submitted application request
### Current Behavior

The Manage page* in the registrar does not currently display an applicant's requested domain or alternate domains. 

*Manage Page = The page users can access after submitting a request by clicking "Manage" on their dashboard.

### Expected Behavior

When viewing the Manage page, applicants should see their requested domain and alternate domains.

### Steps to Reproduce

1) Submit a domain request in the registrar
2) On the registrar dashboard, click on the "Manage" link next to that domain request
3) View the info on that page

### Environment (optional)

_No response_

### Additional Context (optional)

Take a look at the review and submit page on the domain request

### PR DESCRIPTION
**Pull request by dave-kennedy-ecs**
## Ticket

Resolves #685 

## Changes

- new stanza in application_status.html which displays .gov domain section for requested domain and alternate domains
- new block in summary_item.html which formats the above section

## Setup

- go to home page
- click manage next to existing domain request
- check for existence of .gov domain section in the display.  verify this contains requested domain and alternate domains
- note: check a case when there are no alternate domains as well

#### Satisfied acceptance criteria and met development standards

- [x] Met the acceptance criteria, or will meet them in a subsequent PR
- [x] Created/modified automated tests
- [x] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [x] Messaged on Slack or in standup to notify the team that a PR is ready for review

#### Ensured code standards are met (Original Developer)

- [x] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [x] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [x] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [x] Reviewed this code and left comments
- [x] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [x] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots

Example of request with multiple alt domains
---
Example with list of alt domains

Example of request with one alt domain
---
Example with one alt domain

Example of request with no alt domains
---
Example with no alt domain

### CODE REVIEW

**Comment by h-m-f-t** [comment]
Thanks @dave-kennedy-ecs! I think "easy-road.gov" and "remember-enough.gov" should be under a different header than `.gov domain`, lest we give users the impression they were requesting those too. 

The label in the request process is "Alternate domains"👇, though I think in a "shopping card/checkout" context we should probably use something like "Request for alternate domain". Designer feedback welcome.

image

**Comment by dave-kennedy-ecs** [comment]
@designers the requested domain and alternative domains are displayed this way (both under the .gov domain heading) on the domain application review page.  if we do change the headers here on this ticket, it may be worth taking a look at the domain application review page and consider if the change should happen there as well

**Comment by dave-kennedy-ecs** [comment]
Modified to split '.gov domain' and 'Alternative domains' into separate sections, and properly set the alt domains label to match Alternative domains.  Included new screenshots in the PR.

**Comment by Katherine-Osos** [comment]
New ticket to apply changes in other instances created: #956

**Review by rachidatecs — APPROVED** [review]

**Pull request merged**
