### PR TITLE
Setup USWDS

### LINKED ISSUE #79: Add routes for USWDS
Setup installation for USWDS and add initial routes to our project https://designsystem.digital.gov/documentation/getting-started/developers/phase-one-install/

### PR DESCRIPTION
**Pull request by igorkorenfeld**
## 🗣 Description ##

This PR setups up the USWDS folders and assets using `uswds-compile` based on [guidance from
USWDS](https://designsystem.digital.gov/documentation/getting-started/developers/phase-one-install/). It also adds a node service to docker-compose to setup scss compliation within the docker container. Finally, it adds a test template to test the routes and USWDS settings and styles. 

This is part of #79, but does not including error routing, which I'll work on next as a separate PR. 

## ❓Questions for the reviewer(s) ##
- Is this the correct approach?
- Do we ever actually want to have the gulp init script run from the docker container, or would it be better to only setup build/compilation? Because init overwrites with brand new settings and styles files, I wonder if it's best to only have init run once.

### CODE REVIEW

**Comment by SSPJ** [comment]
@igorkorenfeld I think we'll need a strategy for making this Pull Request smaller. I can't review it because GitHub is running my CPU up to 100% and the page is crashing before I can scroll to the bottom (thanks, Microsoft!) Let's chat about it tomorrow, time permitting.

Also, great job getting the Docker piece working! 🥇

**Comment by igorkorenfeld** [comment]
That sounds like a plan! I was hoping that was only affecting me while I was creating the PR, but unfortunately not.

**Comment by loganmeetsworld** [comment]
For acceptance criteria for this I'd like to be able to run it locally and deploy it either to our sandbox or unstable environment successfully.

**Comment by neilmb** [comment]
> For acceptance criteria for this I'd like to be able to run it locally and deploy it either to our sandbox or unstable environment successfully.

Confirming that I have been able to run it locally in a fresh checkout with just `cd src/; docker-compose up`, waiting for USWDS compilation to finish and then loading a well-styled page at `localhost:8080`.

**Comment by loganmeetsworld** [comment]
Not serving as a formal review (I think @neilmb was going to review) but I am all good on documentation/acceptance criteria! This is really awesome work @igorkorenfeld 🥳

**Review by neilmb — APPROVED** [review]
LGTM, 100% approved, this is fantastic.

**Comment by igorkorenfeld** [comment]
Thanks for all the help everyone!

**Pull request merged**
