### PR TITLE
Remove "Archive" from Domain Management dashboard - Za/861 remove archive

### PR DESCRIPTION
**Pull request by zandercymatics**
## Ticket

Resolves [#861](https://github.com/cisagov/getgov/issues/861)
- Remove the archive table and only show the associated "start a new domain request" button when no active domain requests exist

## Changes

- The 'Archived Domains' section was commented out and a note was added regarding re-implementation post MVP
- Moved the 'Start a new domain request' button inside the else block for '{% if domain_applications %}'  

## Questions for reviewers
- There is a particular edge case where the "start a new domain request" button is displayed twice when no Active Domains exist. The fix for this is pretty simple (not showing that button when there are no active domains), but I am not sure if this is intentional or not as the Figma does not denote this. For the designers, is this something that I should fix? (See screenshots)
- The attached figma on the [ticket](https://github.com/cisagov/getgov/issues/861) makes note of the bug were domains of status approved are duplicated in both tables. This was fixed [here](https://github.com/cisagov/getgov/pull/885), but the ticket was closed. Does this fix need to be added for this ticket?

#### Satisfied acceptance criteria and met development standards

- [x] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [x] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [x] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [x] Checked keyboard navigability
- [x] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [x] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [x] Pulled this branch locally and tested it
- [x] Reviewed this code and left comments
- [x] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [x] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [x] Checked keyboard navigability
- [x] Meets all designs and user flows provided by design/product
- [x] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [x] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots
image
image

### CODE REVIEW

**Comment by zandercymatics** [comment]
Swapped this to a Draft PR as this is awaiting a PR on #861. This fix is done so feel free to check it out if you'd like, but it won't be accessible on my sandbox until then

**Comment by therealslimhsiehdy** [comment]
LGTM for now other than the double button capability which I think the designers will be a better fit to answer than me -- great quick fix + questions mate!

**Comment by abroddrick** [comment]
> Does this fix need to be added for this ticket?

no it does not. That is covered elsewhere this should just be removing the archive and the duplcate button issue.

**Comment by abroddrick** [comment]
How did you test with no preloaded data? to verify the button in fact still appears when there are no active requests?

**Comment by zandercymatics** [comment]
@abroddrick 
> How did you test with no preloaded data? to verify the button in fact still appears when there are no active requests?

Using /admin, I deleted every domain application / domain information object that existed locally (select all on the tables). I'd just run the project again once I needed data

**Comment by abroddrick** [comment]
@therealslimhsiehdy did you check off the designer ones? Also sorry y'all that spacing is somehow messed up for the code reviewer doing user facing testing. Rebecca did you already test this to see if you could see the button appearing? (I don't want to delete all my domains yet, but I can )

**Comment by therealslimhsiehdy** [comment]
> @therealslimhsiehdy did you check off the designer ones? Also sorry y'all that spacing is somehow messed up for the code reviewer doing user facing testing. Rebecca did you already test this to see if you could see the button appearing? (I don't want to delete all my domains yet, but I can )

I didn't because I thought that was reserved for Gaby and Katherine (also good catch, I should've went through the boxes when I went thru the PR before) 😬 Button is appearing as expected (although there is two buttons, but looks like the top was was noted as a duplicate and will be removed!)

**Comment by zandercymatics** [comment]
> @therealslimhsiehdy did you check off the designer ones? Also sorry y'all that spacing is somehow messed up for the code reviewer doing user facing testing. Rebecca did you already test this to see if you could see the button appearing? (I don't want to delete all my domains yet, but I can )

Nope that was me! I somehow misread 'Validated user-facing changes as a designer' as 'Validated user-facing changes as the developer' in the markdown. Sorry about that!
Unchecked but I did do all those things, though.

**Review by abroddrick — APPROVED** [review]
Looks good!

**Comment by Katherine-Osos** [comment]
@zandercymatics Can you let designers know when this is available to review in your sandbox?

**Comment by zandercymatics** [comment]
@Katherine-Osos Yeah for sure, I'll send a ping here an also make mention of that in disco

**Review by Katherine-Osos — APPROVED** [review]

**Pull request merged**
