### PR TITLE
Improve request received email

### LINKED ISSUE #416: Update Confirmation Email for Submitted Domain

### PR DESCRIPTION
**Pull request by neilmb**
# Improve request received email #

## 🗣 Description ##

This improves the plain text email that we send to registrants when they submit a new domain application. It includes a summary of their application along with an explanation of next steps.

Screen Shot 2023-04-10 at 1 42 49 PM

Formatting plain text documents using Django's template system can be tricky as it was designed for HTML which is whitespace-insensitive. This PR uses Django's `{% spaceless %}` tag along with tests that explicitly check how many newlines end up between items.

## 💭 Motivation and context ##

Closes #416

### CODE REVIEW

**Review by kewlguy781 — APPROVED** [review]
Codewise, Look good to me. The only question I have about this is, do we need to have "do not reply to this email as it is done automated" text in the email. Something to consider @michelle-rago @igorkorenfeld

**Comment by michelle-rago** [comment]
> Codewise, Look good to me. The only question I have about this is, do we need to have "do not reply to this email as it is done automated" text in the email. Something to consider @michelle-rago @igorkorenfeld

Good question. We should check with @h-m-f-t on whether or not this email should receive replies.

**Review by michelle-rago — COMMENTED** [review]
Looking good, @neilmb! I'm seeing some font color differences. Is that just something happening here or is it intentional?

**Comment by h-m-f-t** [comment]
> > Codewise, Look good to me. The only question I have about this is, do we need to have "do not reply to this email as it is done automated" text in the email. Something to consider @michelle-rago @igorkorenfeld
> 
> Good question. We should check with @h-m-f-t on whether or not this email should receive replies.

We chatted about this question a bit at https://cisa-corp.slack.com/archives/C03QM0JGSQG/p1679670277935509. We should plan for a Reply-To: header, and the address should probably be dotgov@cisa.dhs.gov for now (eventually a help desk system).

**Pull request merged**
