### PR TITLE
Ticket #2352: Edit suborganization on portfolio domains

### LINKED ISSUE #2352: Portfolio user can view and update suborganization
### Issue description

Portfolio user can view and update suborganization for their portfolio. Suborganization is a required field for the Portfolio. 

### Acceptance criteria

- [ ] Portfolio user can view the suborganization for their portfolio
- [ ] Portfolio user can update and save suborganization for their portfolio 
   - [ ] provide save successfully message to user
- [ ] Portfolio user can not leave suborganization field blank
   - [ ] provide information message that suborganization is required
- [ ] Portfolio user can search the suborganization from drop-down
   - [ ] provide reset the search

### Additional context

Per Alysia:  this whole page should be one ticket (including save and the success messages). Note that there is no option to select nothing, and if the person clicks the x on the search then the x returns the box to the initial input value.

### Links to other issues

_No response_

### PR DESCRIPTION
**Pull request by zandercymatics**
## Ticket

Resolves #2352 

## Changes

- Added a edit page for suborganization
- Added a readonly view for the suborganization page
- Added a custom combobox widget

## Context for reviewers
This PR adds an edit and readonly view for suborganizations on portfolios. 

The edit view is only accessible when:
1. You are in "portfolio mode"
2. The domain your looking at exists in a "UserDomainRole" record with your user
3. You have the portfolio role "ADMIN"

Otherwise, when `#1`, `#2` and `#3` are true - you will see the edit mode. 

When only `#1` and `#3` are true - the domain will be in the readonly state.

To see this specific readonly mode, `#1` and `#2` must be true but `#3` must be a role like ADMIN_READONLY or MEMBER with a view all domains permission

## Setup
Enable the `organization_feature` flag and do the following:
1. Add a portfolio to your user
2. Add the "ADMIN" portfolio role to your user
3. Add a UserDomainRole record, add your user and a domain
4. Add said portfolio to the domain you referenced in step 3

To edit the suborg field:
1. On the home page, go to domains and click "edit" on a record
2. Click on the suborganization field, make changes

To view the "readonly" mode for suborg:
1. Change your portfolio role from ADMIN to "ADMIN_READONLY"
2. On the home page, go to domains and click on suborganization

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

### CODE REVIEW

**Comment by asaki222** [comment]
I turned on the waffle flags for organization name, and profile. When I turned them on,  my one domain disappeared. 


Screenshot 2024-08-09 at 5 24 26 PM


Screenshot 2024-08-09 at 5 22 22 PM

**Comment by asaki222** [comment]
> @asaki222 Was this after adding the portfolio to the domain you are referring to? I think that view only displays domains that exist under that bundle of portfolios

adding the portfolio to the domain helped with the issue of the domains not appearing under the domains tab.

**Review by asaki222 — APPROVED** [review]

**Comment by dave-kennedy-ecs** [comment]
image

[Blocking] The readonly view of the suborganization shows the id of the suborganization rather than the suborganization name

**Review by dave-kennedy-ecs — APPROVED** [review]
Left one blocking comment that I think needs to be addressed before merge.

Tested locally.  Reviewed code.  Appropriate application of permissions throughout for portfolio.  Some good code additions in this PR for a combo box utility and a custom filter.  Code looks good.  Approving, assuming the one blocking comment will be resolved before merge.  Nice job

**Pull request merged**
