### PR TITLE
Mr/domain examples

### PR DESCRIPTION
**Pull request by michelle-rago**
# Updated domain examples and some intro text #

## 🗣 Description ##

Added examples that comply with guidance
Most of these examples are being used (meaning the sites are active)
Added links to Census files

## 💭 Motivation and context ##

Improve the domain examples; include more variety.

### CODE REVIEW

**Comment by michelle-rago** [comment]
@neilmb Good morning! I'm not sure what the error is here. Can you take a look? Thank you!

**Comment by neilmb** [comment]
@michelle-rago The text "BlufftonIndiana.gov" was being looked for in one of our test cases (registrar/tests/test_views.py under "test_application_dotgov_domain_dynamic_text"). With the new example text, the test case needs to be updated to match. I think you should be able to do it by editing that test file, but I am also happy to do it.

**Comment by michelle-rago** [comment]
@neilmb Fixed and thank you!

**Review by neilmb — APPROVED** [review]
Looks good to me.

**Pull request merged**
