### PR TITLE
ISSUE #1686: Disallow users to submit an incomplete form

### LINKED ISSUE #1686: Requestors shouldn't be able to submit a request with missing information
### Current Behavior

Domain requestor can submit domain request with missing information

1. Start a new domain request for a given org type (e.g., School District) and complete the domain request application until the final confirmation page Review and submit your domain request. 
2. Go back to Organization type and mailing address and change the organization type (e.g., State). You will be redirected to a new state-specific form for Election Offices. 
3. Do not submit anything on this form and redirect back to the Review and submit your domain request form. 
4. You are able to successfully submit this domain request even though the required Election Offices form is incomplete.

### Expected Behavior

Domain requestor should not be able to submit request with missing information.

### Steps to Reproduce

1. Start a new domain request for a given org type (e.g., School District) and complete the domain request application until the final confirmation page Review and submit your domain request. 
2. Go back to Organization type and mailing address and change the organization type (e.g., State). You will be redirected to a new state-specific form for Election Offices. 
3. Do not submit anything on this form and redirect back to the Review and submit your domain request form. 
4. You are able to successfully submit this domain request even though the required Election Offices form is incomplete.

image
image
image

### Acceptance Criteria

- [ ] Fire page-level alert upon submit of an incomplete form on the final review page.
  - [ ] _option 1_: attempt to scroll to the top and locate where the error is. 
  - [ ] _option 2_: put a generic error message above the submit button, _without_ indicating specific sections that are incomplete
- [ ] log the occurrences to determine incidence of this error.
- [ ]  Confirm with Design for exact working of message during PR review.
### Environment

Staging

### Additional Context

Identified in pre-launch testing. See [issues](https://docs.google.com/document/d/1GvNzvdFOHL8jIiuDfmcxAFXeXXpbkoQx4XkRtAfSVOw/edit)

### Issue Links

_No response_

### PR DESCRIPTION
**Pull request by therealslimhsiehdy**
## Ticket

Resolves #1686 

## Changes

- On the review page if the request form is not filled out fully:
- Display in red where in the form that it's Incomplete
- When you click submit (and subsequently try to submit the form), the modal should pop up with a "Return to request" to fix any incomplete issue(s) with NO cancel button to display
- The modal should also have [new wording as seen here](https://docs.google.com/document/d/1EHMzgmig6vaSFRvCiih87Cx38lD2rWrkEE4BzDzev9Q/edit#heading=h.e4nbu3qrt76y)
- Lots of new spicy logic and unit tests 

## Context for reviewers

For users that fill out the whole form, and then change their generic organization type (ie Federal to Tribal) -- we make sure new parts of the form (ie for Tribal, they'll need Tribe Name and Election field) are filled out and that they can't submit an incomplete form and are nudged to go back to fix those incomplete/missing sections.

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots
Screenshot 2024-05-28 at 5 15 13 PM

Screenshot 2024-05-31 at 2 57 54 PM

### CODE REVIEW

**Comment by Katherine-Osos** [comment]
@therealslimhsiehdy Can you update the modal message, as follows: 

**Your request form is incomplete**
This request cannot be submitted yet. Return to the request and visit the steps that are marked as “incomplete.”

-----
That's my only edit - can approve after that's updated.

**Comment by Katherine-Osos** [comment]
@abroddrick Once the content edit (above) is made, this ticket can be approved from design side. I'm heading OOO, so didn't want this to hold things up. Can you verify this change when it's ready?

**Comment by therealslimhsiehdy** [comment]
> @abroddrick Once the content edit (above) is made, this ticket can be approved from design side. I'm heading OOO, so didn't want this to hold things up. Can you verify this change when it's ready?

I've updated the wording in the screenshot section and the tests, feel free to verify as well on my sandbox!

**Review by abroddrick — APPROVED** [review]
Approved on the design side, you're good to merge

**Pull request merged**
